#!/bin/bash

case $1 in
"create-users")
  curl -0 -v -X POST http://localhost:8080/api/v0/users \
  -H "Expect:" \
  -H 'Content-Type: application/json; charset=utf-8' \
  --data-binary @- << EOF
  {
      "name": "i.medvedev"
  }
EOF
  curl -0 -v -X POST http://localhost:8080/api/v0/users \
  -H "Expect:" \
  -H 'Content-Type: application/json; charset=utf-8' \
  --data-binary @- << EOF
  {
      "name": "e.petrov"
  }
EOF
  curl -0 -v -X POST http://localhost:8080/api/v0/users \
  -H "Expect:" \
  -H 'Content-Type: application/json; charset=utf-8' \
  --data-binary @- << EOF
  {
      "name": "v.tsarev"
  }
EOF
  curl -0 -v -X POST http://localhost:8080/api/v0/users \
  -H "Expect:" \
  -H 'Content-Type: application/json; charset=utf-8' \
  --data-binary @- << EOF
  {
      "name": "m.smirnov"
  }
EOF
  ;;
"update-users")
  curl -0 -v -X PUT http://localhost:8080/api/v0/users/i.medvedev \
  -H "Expect:" \
  -H 'Content-Type: application/json; charset=utf-8' \
  --data-binary @- << EOF
  {
      "contacts":{
           "call": "+7 111-111-1111",
           "email": "i.medvedev@student.com",
           "slack": "i.medvedev",
           "sms": "+7 111-111-1111"    },
      "full_name": "Ivan Medvedev",
      "photo_url": null,
      "time_zone": "Europe/Moscow",
      "active": 1
  }
EOF
  curl -0 -v -X PUT http://localhost:8080/api/v0/users/e.petrov \
  -H "Expect:" \
  -H 'Content-Type: application/json; charset=utf-8' \
  --data-binary @- << EOF
  {
      "contacts":{
           "call": "+7 111-111-1112",
           "email": "e.petrov@student.com",
           "slack": "e.petrov",
           "sms": "+7 111-111-1112"    },
      "full_name": "Egor Petrov",
      "photo_url": null,
      "time_zone": "Europe/Moscow",
      "active": 1
  }
EOF
  curl -0 -v -X PUT http://localhost:8080/api/v0/users/v.tsarev \
  -H "Expect:" \
  -H 'Content-Type: application/json; charset=utf-8' \
  --data-binary @- << EOF
  {
      "contacts":{
           "call": "+7 111-111-1113",
           "email": "v.tsarev@student.com",
           "slack": "v.tsarev",
           "sms": "+7 111-111-1113"    },
      "full_name": "Vasiliy Tsarev",
      "photo_url": null,
      "time_zone": "Europe/Moscow",
      "active": 1
  }
EOF
  curl -0 -v -X PUT http://localhost:8080/api/v0/users/m.smirnov \
  -H "Expect:" \
  -H 'Content-Type: application/json; charset=utf-8' \
  --data-binary @- << EOF
  {
      "contacts":{
           "call": "+7 111-111-1114",
           "email": "m.smirnov@student.com",
           "slack": "m.smirnov",
           "sms": "+7 111-111-1114"    },
      "full_name": "Maksim Smirnov",
      "photo_url": null,
      "time_zone": "Europe/Moscow",
      "active": 1
  }
EOF
  ;;
"update-teams")
  curl -0 -v -X PUT http://localhost:8080/api/v0/teams/team-1 \
  -H "Expect:" \
  -H 'Content-Type: application/json; charset=utf-8' \
  --data-binary @- << EOF
  {
       "name": "team-1",
       "scheduling_timezone": "Europe/Moscow",
       "email": "team-1@student.com",
       "slack_channel": "#team-1"
  }
EOF
  curl -0 -v -X PUT http://localhost:8080/api/v0/teams/team-2 \
  -H "Expect:" \
  -H 'Content-Type: application/json; charset=utf-8' \
  --data-binary @- << EOF
  {
       "name": "team-2",
       "scheduling_timezone": "Europe/Moscow",
       "email": "team-2@student.com",
       "slack_channel": "#team-2"
  }
EOF
  ;;
"delete-teams")
  curl -0 -v -X DELETE http://localhost:8080/api/v0/team-1
  curl -0 -v -X DELETE http://localhost:8080/api/v0/team-2
  ;;
"delete-all")
  mysql -u root -p1234 -e "show databases" | grep -v Database | grep -v mysql | grep -v information_schema | gawk '{print "drop database `" $1 "`;select sleep(0.1);"}' | mysql -u root -p1234
  mysql -u root -p1234 < /opt/oncall/db/schema.v0.sql
  ;;
 "-h" | *)
 echo "Available options:"
 echo "create-users"
 echo "update-users"
 echo "update-teams"
 echo "delete-teams"
 echo "delete-all - delete all oncall data from db"
 echo "-h help"
   ;;
 esac
 